apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: helloworld
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    amiFamily: AmazonLinux2
    minsize: 2
    maxsize: 3
    ssh:
      allow: true
      publicKeyName: devops-east2
